version: '3.11'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: choredb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/choredb
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: sh -c "flask db upgrade && flask setup && flask run"
    volumes:
      - homechore/static:/static