"""Add points to User and point_value to Chore

Revision ID: ca881b28b488
Revises: fa8537f27f15
Create Date: 2025-03-05 20:46:57.256260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca881b28b488'
down_revision = 'fa8537f27f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('point_value', sa.Integer(), nullable=False, server_default='10'))

    op.add_column('users', sa.Column('points', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    op.drop_column('chores', 'point_value')
    # ### end Alembic commands ###
