"""Add due_days column to Chore model

Revision ID: d7d9b7cec4e3
Revises: c72b58875791
Create Date: 2025-02-27 19:55:48.022291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7d9b7cec4e3'
down_revision = 'c72b58875791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('due_days', sa.String(length=255), nullable=True))
    op.alter_column('chores', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('unique_chore_per_household', 'chores', type_='unique')
    op.drop_constraint('chores_household_id_fkey', 'chores', type_='foreignkey')
    op.create_foreign_key(None, 'chores', 'households', ['household_id'], ['id'])
    op.drop_column('chores', 'frequency')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_chore_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'chores', ['chore_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_household_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'households', ['household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_household_id_fkey', 'users', 'households', ['household_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_chore_id_fkey', 'notifications', 'chores', ['chore_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('chores', sa.Column('frequency', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chores', type_='foreignkey')
    op.create_foreign_key('chores_household_id_fkey', 'chores', 'households', ['household_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('unique_chore_per_household', 'chores', ['household_id', 'name'])
    op.alter_column('chores', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('chores', 'due_days')
    # ### end Alembic commands ###
