"""Add last_completed_by column to Chore

Revision ID: dcc2b0598cfe
Revises: ca881b28b488
Create Date: 2025-03-14 21:33:31.033698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc2b0598cfe'
down_revision = 'ca881b28b488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('last_completed_by', sa.Integer(), nullable=True))
    op.alter_column('chores', 'point_value',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.create_index(op.f('ix_chores_assigned_to'), 'chores', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'chores', 'users', ['last_completed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chores', type_='foreignkey')
    op.drop_index(op.f('ix_chores_assigned_to'), table_name='chores')
    op.alter_column('chores', 'point_value',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.drop_column('chores', 'last_completed_by')
    # ### end Alembic commands ###
