"""Added cooldown value to chores

Revision ID: fa8537f27f15
Revises: 5385e846f53e
Create Date: 2025-02-28 10:42:05.708378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8537f27f15'
down_revision = '5385e846f53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('cooldown', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'cooldown')
    # ### end Alembic commands ###
