name: Publish Docker Image

on:
  push:
    branches:
      - main  # Build on every push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/islandjon/homechore:latest .
          docker tag ghcr.io/islandjon/homechore:latest ghcr.io/islandjon/homechore:$(date +%Y%m%d)

      - name: Push Docker Image
        run: |
          docker push ghcr.io/islandjon/homechore:latest
          docker push ghcr.io/islandjon/homechore:$(date +%Y%m%d)
